name: Build

on:
  workflow_call:
    inputs:
      sha:        
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      name: Checkout source code
      id: git-checkout
      with:
        ref: ${{ inputs.sha }}

    - name: Login to GitHub Container Registry
      id: Registry login
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
